version: '3.8'

services:
  web:
    build: .
    command: python -m uvicorn ninja_project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      - DJANGO_SECRET_KEY  
      - DJANGO_DEBUG  
      - DJANGO_ALLOWED_HOSTS  